# Copyright (c) 2019 Shapelets.io
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language: csharp

env:
  LD_LIBRARY_PATH: /usr/local/lib:/usr/local/include:$LD_LIBRARY_PATH
  DYLD_FALLBACK_LIBRARY_PATH: /usr/local/include:$DYLD_FALLBACK_LIBRARY_PATH
  BOOST_PATH: Libraries/boost_1_67_0:$BOOST_PATH
  AF_PATH: /opt/arrayfire-3:$AF_PATH
  KHIVA_PATH: ./khiva-library:$KHIVA_PATH
  LDFLAGS: -L/usr/local/opt/openssl/lib
  CPPFLAGS: -I/usr/local/opt/openssl/include
  PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig
  PATH: /usr/local/opt/openssl/bin:/usr/bin/:/bin/:/usr/local/bin:/usr/local/lib:/usr/local/share:/usr/local/include:/usr/lib:$AF_PATH/lib:$KHIVA_PATH/lib:$PATH

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      sudo: required
      mono: latest
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/installers
          - ${HOME}/.m2
          - ${HOME}/.conan
          - ${TRAVIS_BUILD_DIR}/cmake
    - os: osx
      mono: latest
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/installers
          - ${HOME}/.m2
          - ${HOME}/.conan
          - ${TRAVIS_BUILD_DIR}/cmake
          - ${HOME}/Library/Caches/Homebrew
          - ${HOME}/.pyenv

install:
  - source .CI/travis/install_mono.sh
  - source .CI/travis/install-arrayfire.sh
  - source .CI/travis/install-khiva.sh
script:
  - source .CI/travis/build_and_test_mono.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)